### ISSUE TITLE
Json messages not working :( 

### ISSUE THREAD

**Issue by SlamTheHam** [Leomixer17/uSkAddon#2]
![image](https://user-images.githubusercontent.com/34078391/45691744-2a253400-bb27-11e8-8935-4e6b447acc6a.png)

my script https://pastebin.com/sLepudjm

**Comment by leonardo-dgs** [comment]
What version of Skript are you using?

**Comment by SlamTheHam** [comment]
latest

**Comment by leonardo-dgs** [comment]
Latest Skript version is unstable, this addon will be updated when Skript will become stable

**Comment by SlamTheHam** [comment]
i'm not using the a.1.13 versions
its the lastest stable version
